
package CalculadoraPace;


public class CalculadoraJframe extends javax.swing.JFrame {

    public CalculadoraJframe() {
        initComponents();
    }
    Double valor1, valor2,x;
    String operacao;
    int contador = -1;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Botao1 = new javax.swing.JButton();
        Botao2 = new javax.swing.JButton();
        Botao3 = new javax.swing.JButton();
        Botao4 = new javax.swing.JButton();
        OperadorDivisao = new javax.swing.JButton();
        Limpatela = new javax.swing.JButton();
        Botao5 = new javax.swing.JButton();
        Botao6 = new javax.swing.JButton();
        Botao7 = new javax.swing.JButton();
        Botao8 = new javax.swing.JButton();
        Botao9 = new javax.swing.JButton();
        Desliga = new javax.swing.JButton();
        Botao00 = new javax.swing.JButton();
        Botao0 = new javax.swing.JButton();
        OperadorRaiz1 = new javax.swing.JButton();
        OperadorExponencial = new javax.swing.JButton();
        OperacaoVirgula = new javax.swing.JButton();
        OperadorIgualdade = new javax.swing.JButton();
        OperadorSoma = new javax.swing.JButton();
        OperadorVezes = new javax.swing.JButton();
        OperacaoPorcentagem1 = new javax.swing.JButton();
        OperadorMenos = new javax.swing.JButton();
        Resultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora Pacetech");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridLayout(4, 6, 15, 15));

        Botao1.setText("1");
        Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao1ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao1);

        Botao2.setText("2");
        Botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao2ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao2);

        Botao3.setText("3");
        Botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao3ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao3);

        Botao4.setText("4");
        Botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao4ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao4);

        OperadorDivisao.setText("/");
        OperadorDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorDivisaoActionPerformed(evt);
            }
        });
        jPanel2.add(OperadorDivisao);

        Limpatela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Limpatela.setText("AC");
        Limpatela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpatelaActionPerformed(evt);
            }
        });
        jPanel2.add(Limpatela);

        Botao5.setText("5");
        Botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao5ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao5);

        Botao6.setText("6");
        Botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao6ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao6);

        Botao7.setText("7");
        Botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao7ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao7);

        Botao8.setText("8");
        Botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao8ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao8);

        Botao9.setText("9");
        Botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao9ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao9);

        Desliga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Desliga.setText("OFF");
        Desliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesligaActionPerformed(evt);
            }
        });
        jPanel2.add(Desliga);

        Botao00.setText("00");
        Botao00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao00ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao00);

        Botao0.setText("0");
        Botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao0ActionPerformed(evt);
            }
        });
        jPanel2.add(Botao0);

        OperadorRaiz1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OperadorRaiz1.setText("Raíz");
        OperadorRaiz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorRaiz1ActionPerformed(evt);
            }
        });
        jPanel2.add(OperadorRaiz1);

        OperadorExponencial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperadorExponencial.setText("x^n");
        OperadorExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorExponencialActionPerformed(evt);
            }
        });
        jPanel2.add(OperadorExponencial);

        OperacaoVirgula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperacaoVirgula.setText(".");
        OperacaoVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacaoVirgulaActionPerformed(evt);
            }
        });
        jPanel2.add(OperacaoVirgula);

        OperadorIgualdade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperadorIgualdade.setText("=");
        OperadorIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorIgualdadeActionPerformed(evt);
            }
        });
        jPanel2.add(OperadorIgualdade);

        OperadorSoma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperadorSoma.setText("+");
        OperadorSoma.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        OperadorSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorSomaActionPerformed(evt);
            }
        });
        jPanel2.add(OperadorSoma);

        OperadorVezes.setText("*");
        OperadorVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorVezesActionPerformed(evt);
            }
        });
        jPanel2.add(OperadorVezes);

        OperacaoPorcentagem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperacaoPorcentagem1.setText("%");
        OperacaoPorcentagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperacaoPorcentagem1ActionPerformed(evt);
            }
        });
        jPanel2.add(OperacaoPorcentagem1);

        OperadorMenos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OperadorMenos.setText("-");
        OperadorMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperadorMenosActionPerformed(evt);
            }
        });
        jPanel2.add(OperadorMenos);

        Resultado.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Resultado.setAlignmentX(0.0F);
        Resultado.setBorder(new javax.swing.border.MatteBorder(null));
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pacetechcalc1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel3.setText("\"Desculpas não trazem resultados\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(308, 308, 308))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(189, 189, 189))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OperacaoVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacaoVirgulaActionPerformed
        // virgula
        Resultado.setText(Resultado.getText()+ ".");

    }//GEN-LAST:event_OperacaoVirgulaActionPerformed

    private void OperadorExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorExponencialActionPerformed
        valor1= Double.parseDouble(Resultado.getText());
        Resultado.setText("");
        operacao="exponencial";
    }//GEN-LAST:event_OperadorExponencialActionPerformed

    private void LimpatelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpatelaActionPerformed
        Resultado.setText("");
    }//GEN-LAST:event_LimpatelaActionPerformed

    private void OperadorDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorDivisaoActionPerformed
        valor1 = Double.parseDouble(Resultado.getText());
        Resultado.setText("");
        operacao = "divisao";
    }//GEN-LAST:event_OperadorDivisaoActionPerformed

    private void OperadorMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorMenosActionPerformed
        valor1= Double.parseDouble(Resultado.getText());
        Resultado.setText("");
        operacao = "subtracao";

    }//GEN-LAST:event_OperadorMenosActionPerformed

    private void OperadorVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorVezesActionPerformed
        valor1= Double.parseDouble(Resultado.getText());
        Resultado.setText("");
        operacao = "multiplicacao";
    }//GEN-LAST:event_OperadorVezesActionPerformed

    private void OperadorIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorIgualdadeActionPerformed
        valor2 = Double.parseDouble(Resultado.getText());
        if (operacao == "soma"){
            Resultado.setText(String.valueOf(valor1 + valor2));}
        else if (operacao == "subtracao"){
            Resultado.setText(String.valueOf(valor1 - valor2));
        }

        else if (operacao == "multiplicacao"){
            Resultado.setText(String.valueOf(valor1 * valor2));
        }
        else if (operacao == "divisao"){
            Resultado.setText(String.valueOf(valor1/valor2));

        }
        else if (operacao == "exponencial"){
            Resultado.setText(String.valueOf(Math.pow(valor1, valor2)));
        }
        else if (operacao == "raizquadrada"){
            valor2=0.5;
            Resultado.setText(String.valueOf(Math.pow(valor1, valor2)));}
        else if (operacao == "porcentagem"){
            Resultado.setText(String.valueOf((valor1/valor2)*100 + "%"));
        }
        
            //}

        //}

    }//GEN-LAST:event_OperadorIgualdadeActionPerformed

    private void OperadorSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorSomaActionPerformed
        valor1 = Double.parseDouble(Resultado.getText());
        Resultado.setText("");
        operacao = "soma";

    }//GEN-LAST:event_OperadorSomaActionPerformed

    private void Botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao0ActionPerformed
        // Tecla 0
        Resultado.setText(Resultado.getText()+ "0");
    }//GEN-LAST:event_Botao0ActionPerformed

    private void Botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao9ActionPerformed
        // Tecla 9
        Resultado.setText(Resultado.getText()+ "9");
    }//GEN-LAST:event_Botao9ActionPerformed

    private void Botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao8ActionPerformed
        // Botao 8
        Resultado.setText(Resultado.getText() + "8");
    }//GEN-LAST:event_Botao8ActionPerformed

    private void Botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao7ActionPerformed
        // Botao7
        Resultado.setText(Resultado.getText()+ "7");
    }//GEN-LAST:event_Botao7ActionPerformed

    private void Botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao6ActionPerformed
        // Botao 6
        Resultado.setText(Resultado.getText()+ "6");
    }//GEN-LAST:event_Botao6ActionPerformed

    private void Botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao5ActionPerformed
        // Botao 5
        Resultado.setText(Resultado.getText()+ "5");
    }//GEN-LAST:event_Botao5ActionPerformed

    private void Botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao4ActionPerformed
        // Botao 4
        Resultado.setText(Resultado.getText()+ "4");
    }//GEN-LAST:event_Botao4ActionPerformed

    private void Botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao3ActionPerformed
        // Botao 3
        Resultado.setText(Resultado.getText()+ "3");
    }//GEN-LAST:event_Botao3ActionPerformed

    private void Botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao2ActionPerformed
        // Botao 2
        Resultado.setText(Resultado.getText() + "2");
    }//GEN-LAST:event_Botao2ActionPerformed

    private void Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao1ActionPerformed
        // Botão 1
        Resultado.setText(Resultado.getText()+"1");

    }//GEN-LAST:event_Botao1ActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // Tela

    }//GEN-LAST:event_ResultadoActionPerformed

    private void DesligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesligaActionPerformed
        // OFF
        Resultado.setText("");
    }//GEN-LAST:event_DesligaActionPerformed

    private void OperadorRaiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperadorRaiz1ActionPerformed
        // TODO add your handling code here:
        valor1= Double.parseDouble(Resultado.getText());
       
        operacao="raizquadrada";
    }//GEN-LAST:event_OperadorRaiz1ActionPerformed

    private void Botao00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao00ActionPerformed
        // 00
        Resultado.setText(Resultado.getText()+"00");
    }//GEN-LAST:event_Botao00ActionPerformed

    private void OperacaoPorcentagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperacaoPorcentagem1ActionPerformed
        // %
        valor1= Double.parseDouble(Resultado.getText());
        Resultado.setText("");
        operacao="porcentagem";
        
    }//GEN-LAST:event_OperacaoPorcentagem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao0;
    private javax.swing.JButton Botao00;
    private javax.swing.JButton Botao1;
    private javax.swing.JButton Botao2;
    private javax.swing.JButton Botao3;
    private javax.swing.JButton Botao4;
    private javax.swing.JButton Botao5;
    private javax.swing.JButton Botao6;
    private javax.swing.JButton Botao7;
    private javax.swing.JButton Botao8;
    private javax.swing.JButton Botao9;
    private javax.swing.JButton Desliga;
    private javax.swing.JButton Limpatela;
    private javax.swing.JButton OperacaoPorcentagem1;
    private javax.swing.JButton OperacaoVirgula;
    private javax.swing.JButton OperadorDivisao;
    private javax.swing.JButton OperadorExponencial;
    private javax.swing.JButton OperadorIgualdade;
    private javax.swing.JButton OperadorMenos;
    private javax.swing.JButton OperadorRaiz1;
    private javax.swing.JButton OperadorSoma;
    private javax.swing.JButton OperadorVezes;
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
